version: 2.1
orbs:
  win: circleci/windows@2.3.0

jobs:
  test:
    executor: win/default
    steps:
      - run: docker pull mcr.microsoft.com/windows/servercore:1809
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
