version: 2.1
orbs:
  win: circleci/windows@2.3.0

jobs:
  servercore-1809:
    executor: win/default
    steps:
      - run: docker pull mcr.microsoft.com/windows/servercore:1809
  servercore-1903:
    executor: win/default
    steps:
      - run: docker pull mcr.microsoft.com/windows/servercore:1903
  servercore-1909:
    executor: win/default
    steps:
      - run: docker pull mcr.microsoft.com/windows/servercore:1909
  servercore-2019:
    executor: win/default
    steps:
      - run: docker pull mcr.microsoft.com/windows/servercore:2019

workflows:
  version: 2
  build_and_test:
    jobs:
      - servercore-1809
      - servercore-1903
      - servercore-1909
      - servercore-2019
