on:
  push:

jobs:

  build-image:
    runs-on: ubuntu-20.04
    outputs:
      changed-files-list: ${{ steps.check-changed-files.outputs.changed-files-list }}
    steps:
      - uses: actions/checkout@v3
      #- run: du -sh /*/*/ 2> /dev/null
      #- name: Check /usr/local/lib/
      #  run: du -sh /usr/local/lib/*/ 2> /dev/null
      #- name: Check /usr/share
      #  run: du -sh /usr/share/*/ 2> /dev/null

      - run: >
          curl -sLO https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_amd64.deb \
          && sudo dpkg -i duf_0.8.1_linux_amd64.deb

      - run: sudo duf

      - run: >
          sudo rm -rf \
            /opt/az/
#            /bin/X11/ \
#            /home/linuxbrew/ \
#            /lib/jvm/ \
#            /opt/az/ \
#            /opt/hostedtoolcache/ \
#            /usr/share/dotnet/ \
#            /usr/share/swift/ \
#            /usr/local/lib/android/

      - run: sudo duf

      - run: docker build -t csgo-test .

      - run: sudo duf
        if: always()
