on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-20.04
    outputs:
      changed-files-list: ${{ steps.check-changed-files.outputs.changed-files-list }}
    steps:
      - uses: actions/checkout@v3
      - run: du -sh *
      - run: df -h
      - run: docker build -t csgo-test .
      - run: df -h
        if: always()
