on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
      - name: Second Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
          
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
      - name: Second Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
      - name: Purposefully Fail
        run: sleep 5 && exit 1

    
  retry-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job]
    if: always()
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check running jobs
        run: >
          gh run list --repo ${{ github.repository }}
          --json name,startedAt,updatedAt,url,conclusion,databaseId
      - name: List total jobs
        run: >
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs