on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-vm:
    runs-on: windows-2019
    steps:
      - name: Test Command
        run: >
          for %TAG in (hello bla)
          do
            Write-Host "%TAG"

