on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-vm:
    runs-on: windows-2019
    steps:
      - name: First Test
        run: >
          $number = “ubuntu,ubuntu-20,latest”;
          $lists = $number.split(“,”);
          foreach ($letter in $number.split(“,”))
          {
            Write-Host $letter;
            Write-Host "-----";
          }
      - name: Test Command
        run: >
          for %TAG in (hello bla)
          do
            Write-Host "%TAG"

