on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-vm:
    runs-on: windows-2019
    steps:
      - name: First Test
        run: >
          $number = “ubuntu ubuntu-20 latest”;
          $number.count
      - name: Second Test
        run: >
          $letterArray = "a","b","c","d";
          $number = “ubuntu ubuntu-20 latest”;
          foreach ($letter in $number)
          {
            Write-Host $letter;
            Write-Host "-----";
          }
      - name: Test Command
        run: >
          for %TAG in (hello bla)
          do
            Write-Host "%TAG"

