on:
  push:
    branches:
      - changed-files
  pull_request:
    branches:
      - changed-files

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs
      - name: Second Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
