on:
  push:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  changed-files:
    name: Check Changed Files
    runs-on: ubuntu-20.04
    outputs:
      changed-files-list: ${{ steps.check-changed-files.outputs.changed-files-list }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: First Command
        id: check-changed-files
        run: |
          echo 'changed-files-list<<EOF' >> $GITHUB_OUTPUT
          git show --name-only --pretty=format: ${{ github.sha }} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - run: >
          echo "${{ steps.check-changed-files.outputs.changed-files-list }}"

  first-job:
    runs-on: ubuntu-20.04
    needs: changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo ${{ needs.changed-files.outputs.changed-files-list }}
      - run: echo ${{ github.event_name }}
      #- name: First Command
      #  run: |
      #    echo 'CHANGED_FILES<<EOF' >> $GITHUB_ENV
      #    git show --name-only --pretty=format: ${{ github.sha }} >> $GITHUB_ENV
      #    echo 'EOF' >> $GITHUB_ENV
      - run: >
          echo $CHANGED_FILES

      - name: Second Command
        if: contains(${{ env.CHANGED_FILES }}, 'test-a')
        run: >
          echo "LETS GOO"
