on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
      - name: Second Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
          
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}
      - name: Second Command
        run: >
          echo ${{ github.run_id }} &&
          echo ${{ github.job }}

    
  retry-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job]
    steps:
      - name: Check running jobs
        run: gh run list