on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - name: First Command
        run: >
          echo ${{ github.run_id }}

      - name: Second Command
        run: >
          echo ${{ github.run_id }}
          
