on:
  push:

jobs:
  test-push-edit:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create file
        run: touch test.txt

      # make the changes between checkout and push
      - name: push
        uses: actions-x/commit@v6