on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-20.04
    outputs:
      changed-files-list: ${{ steps.check-changed-files.outputs.changed-files-list }}
    steps:
      - uses: actions/checkout@v3
      #- run: du -sh /*/*/ 2> /dev/null
      - name: Check /usr/local/lib/
        run: du -sh /usr/local/lib/*/ 2> /dev/null
      #- name: Check /usr/share
      #  run: du -sh /usr/share/*/ 2> /dev/null

      - run: df -h

      - run: |
          sudo rm -rf /bin/X11/
          sudo rm -rf /home/linuxbrew/
          sudo rm -rf /lib/jvm/
          sudo rm -rf /opt/az/
          sudo rm -rf /opt/hostedtoolcache/
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/share/swift/
          sudo rm -rf /usr/local/lib/android/

      - run: df -h

      - run: docker build -t csgo-test . && df -h
      - run: df -h
        if: always()
