on:
  push:

jobs:

  build-image:
    runs-on: ubuntu-20.04
    outputs:
      changed-files-list: ${{ steps.check-changed-files.outputs.changed-files-list }}
    steps:
      - uses: actions/checkout@v3
      #- run: du -sh /*/*/ 2> /dev/null
      #- name: Check /usr/local/lib/
      #  run: du -sh /usr/local/lib/*/ 2> /dev/null
      #- name: Check /usr/share
      #  run: du -sh /usr/share/*/ 2> /dev/null


      - run: df -h

      - run: whoami
      - run: sudo whoami

      - run: >
          sudo rm -rf \
            /bin/X11/ \
            /home/linuxbrew/ \
            /lib/jvm/ \
            /opt/az/ \
            /opt/hostedtoolcache/ \
            /usr/share/dotnet/ \
            /usr/share/swift/ \
            /usr/local/lib/android/

      - run: df -h

      - run: docker build -t csgo-test . && df -h
      - run: df -h
        if: always()
