on:
  push:
    branches:
      - changed-files
  pull_request:
    branches:
      - changed-files

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: First Command
        run: |
          echo 'CHANGED_FILES<<EOF' >> $GITHUB_ENV
          git show --name-only --pretty=format: ${{ github.sha }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: >
          echo $CHANGED_FILES

      - name: Second Command
        if: contains('${{ env.CHANGED_FILES }}', 'test-a')
        run: >
          echo "LETS GOO"