on:
  release:
    types:
      - created
    branches:
      - 'releases/v**'
    tags-ignore:
      - '!v**'

jobs:
  run-only-tag:
    runs-on: ubuntu-18.04
    steps:
      - name: Get version tag
        run: echo "::set-env name=API_VERSION::$(echo $GITHUB_REF | awk -F '/' '{print $NF}')"
      - name: Test command
        run: echo "$GITHUB_REF" && echo "" && echo "$API_VERSION"
      - name: Check tag convention
        run: '[[ "${API_VERSION:0:1}" == "v" ]] || exit 1'
